<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b7e21121-aba2-41ab-9c24-be278aaef634</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MMLib.SwaggerForOcelot" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Api\Common.Api.ServiceDefaults\Common.Api.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
