<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Infrastructure.Cache\Common.Infrastructure.Cache.csproj" />
    <ProjectReference Include="..\Common.Infrastructure.Contracts\Common.Infrastructure.Contracts.csproj" />
  </ItemGroup>

</Project>
