<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>0239cb11-bad1-446e-955e-85f636502eca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(CommonApi)\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="$(Invoice)\Invoice.Application\Invoice.Application.csproj" />
    <ProjectReference Include="$(Invoice)\Invoice.Controllers\Invoice.Controllers.csproj" />
	<ProjectReference Include="$(InvoiceInfra)\Invoice.Infrastructure.Persistence\Invoice.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
