<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>0239cb11-bad1-446e-955e-85f636502eca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(CommonApi)\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="$(Order)\Order.Application\Order.Application.csproj" />
    <ProjectReference Include="$(Order)\Order.Controllers\Order.Controllers.csproj" />
  </ItemGroup>

</Project>
