<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(CommonInfra)\Common.Infrastructure.Seeder\Common.Infrastructure.Seeder.csproj" />
    <ProjectReference Include="$(SecurityInfra)\Security.Infrastructure.Cache.Key\Security.Infrastructure.Cache.Key.csproj" />
    <ProjectReference Include="$(Product)\Product.Domain\Product.Domain.csproj" />
    <ProjectReference Include="$(ProductInfra)\Product.Infrastructure.Cache.Key\Product.Infrastructure.Cache.Key.csproj" />
  </ItemGroup>

</Project>
