<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Mapster" Version="7.4.0" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(CommonApp)\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="$(SecurityInfra)\Security.Infrastructure.Contracts\Security.Infrastructure.Contracts.csproj" />
    <ProjectReference Include="$(SecurityInfra)\Security.Infrastructure.Messaging\Security.Infrastructure.Messaging.csproj" />
    <ProjectReference Include="$(Security)\Security.Domain\Security.Domain.csproj" />
  </ItemGroup>

</Project>
