<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="$(CommonInfra)\Common.Infrastructure.Messages\Common.Infrastructure.Messages.csproj" />
		<ProjectReference Include="$(Order)\Order.Domain\Order.Domain.csproj" />
	</ItemGroup>
</Project>
