<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<OutputType>Library</OutputType>
	<UserSecretsId>c1c97c64-bb23-4a53-92ee-dd7961403b79</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.11" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
	<PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(LogsInfra)\Logs.Infrastructure.Messaging\Logs.Infrastructure.Messaging.csproj" />
    <ProjectReference Include="$(SecurityInfra)\Security.Infrastructure.Contracts\Security.Infrastructure.Contracts.csproj" />
    <ProjectReference Include="$(SecurityInfra)\Security.Infrastructure.Messaging\Security.Infrastructure.Messaging.csproj" />
    
    <ProjectReference Include="$(Common)\Domain\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="$(Common)\Extensions\Common.Extensions\Common.Extensions.csproj" />
    <ProjectReference Include="..\Common.Infrastructure.Persistence\Common.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
