<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="$(Order)\Order.Application\Order.Application.csproj" />
	  <ProjectReference Include="$(Order)\Order.Domain\Order.Domain.csproj" />
	  <ProjectReference Include="$(CommonApi)\Common.Api.Controllers\Common.Api.Controllers.csproj" />
  </ItemGroup>

</Project>
