<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(CommonApi)\Common.Api.Controllers\Common.Api.Controllers.csproj" />
    <ProjectReference Include="$(Inventory)\Inventory.Application\Inventory.Application.csproj" />
    <ProjectReference Include="$(Inventory)\Inventory.Domain\Inventory.Domain.csproj" />
  </ItemGroup>

</Project>
