<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>0239cb11-bad1-446e-955e-85f636502eca</UserSecretsId>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Api\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="..\Infrastructure\Inventory.Infrastructure.Persistence\Inventory.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Infrastructure\Inventory.Infrastructure.Seeders\Inventory.Infrastructure.Seeders.csproj" />
    <ProjectReference Include="..\Inventory.Application\Inventory.Application.csproj" />
    <ProjectReference Include="..\Inventory.Controllers\Inventory.Controllers.csproj" />
  </ItemGroup>

</Project>
