<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Messages\Response\**" />
    <EmbeddedResource Remove="Messages\Response\**" />
    <None Remove="Messages\Response\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(Common)\Domain\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="$(Common)\Extensions\Common.Extensions\Common.Extensions.csproj" />
    <ProjectReference Include="$(CommonInfra)\Common.Infrastructure.Cache.Key\Common.Infrastructure.Cache.Key.csproj" />
    <ProjectReference Include="$(CommonInfra)\Common.Infrastructure.Cache\Common.Infrastructure.Cache.csproj" />
    <ProjectReference Include="$(CommonInfra)\Common.Infrastructure.Contracts\Common.Infrastructure.Contracts.csproj" />
    <ProjectReference Include="$(CommonInfra)\Common.Infrastructure.Messages\Common.Infrastructure.Messages.csproj" />
    <ProjectReference Include="$(Security)\Security.Domain\Security.Domain.csproj" />
    <ProjectReference Include="$(Security)\Security.Infrastructure.Contracts\Security.Infrastructure.Contracts.csproj" />
  </ItemGroup>

</Project>
