<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Api\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="..\Infrastructure\Order.Infrastructure\Order.Infrastructure.csproj" />
    <ProjectReference Include="..\Order.Application\Order.Application.csproj" />
    <ProjectReference Include="..\Order.Controllers\Order.Controllers.csproj" />
  </ItemGroup>

</Project>
