<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>0239cb11-bad1-446e-955e-85f636502eca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Api\Common.Api\Common.Api.csproj" />
    <ProjectReference Include="..\Infrastructure\Shipping.Infrastructure.Persistence\Shipping.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Infrastructure\Shipping.Infrastructure.Seeders\Shipping.Infrastructure.Seeders.csproj" />
    <ProjectReference Include="..\Shipping.Application\Shipping.Application.csproj" />
    <ProjectReference Include="..\Shipping.Controllers\Shipping.Controllers.csproj" />
  </ItemGroup>
	

</Project>
